name: Dev-Builds
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:8-jdk
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1.0.3
      - run: chmod +x ./gradlew
      - run: ./gradlew clean build publish curseforge
        env:
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: Builds
          path: '**/build/libs/*.jar'
